### ISSUE TITLE
Does this only work with WebPack?

### ISSUE THREAD

**Issue by nemo-omen** [lyohaplotinka/svelte-easyroute#14]
I'm getting an error with the default svelte rollup template and it looks like this packages deps are all WebPack based.

**Comment by lyohaplotinka** [comment]
@nemo-omen, looks like rollup and webpack are working with UMD-modules in different ways. 

I suggest you trying this, it worked for me:

```javascript
// router.js

import _Router from 'svelte-easyroute'
const Router = _Router.default

const router = new Router(...)
```

I will try to fix this in next releases, or add a note in documentation. 

Thank you!

**Comment by lyohaplotinka** [comment]
@nemo-omen 
v2.1.3 is here ( #15), now you can seamlessly use Easyroute with rollup.

Thank you!
