### ISSUE TITLE
RouterOutlet is not defined (Rollup)

### ISSUE THREAD

**Issue by zefman** [lyohaplotinka/svelte-easyroute#2]
Hi,

Thanks for this router, it was working perfectly until the last update. Now I am getting RouterOutlet is not defined when using Rollup. I can see in router.js that the line `// import RouterOutlet from './RouterOutlet.svelte'` is commented out. Was this done in error?

If I uncomment that line everything works again.

Thanks for you help!

**Comment by lyohaplotinka** [comment]
@zefman,

Thank you for opening this issue. Yes, it was my mistake, that happened due to development process. I will try to make everything for this situation will never happen again. 

I updated repository and published new versions on NPM. Now everything should work fine.

Thank yo again!
