### ISSUE TITLE
Fails to compile when webpack excludes node_modules

### ISSUE THREAD

**Issue by ejolly** [lyohaplotinka/svelte-easyroute#5]
Hi thanks for developing this! I'm trying to use it with the svelte 3 webpack template and I followed all the instructions but I get the following error when I try to `npm run dev`:

```
ERROR in ./node_modules/svelte-easyroute-webpack/RouterLink.svelte 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <div class="router-link" on:click={navigateRouter}>
| {#if text && text !== ""}
| {text}
 @ ./src/App.svelte 15:0-67 20:23-33 22:23-33
 @ ./src/main.js
 @ multi ./src/main.js
```

If I edit my `webpack.config.js` to remove `exclude: /node_modules/` under rules, it removes the error and everything works fine. Is this the intended way to set up the router? I'm not all that familiar with webpack, so the default setting of `exclude: /node_modules/` came from the [svelte webpack template](https://github.com/sveltejs/template-webpack)

Here's a link to my project repo (it's just a very simple scaffold), where I noted the line in the `webpack.config.js` file: https://github.com/ejolly/svelte_frontend_driven

**Comment by lyohaplotinka** [comment]
Hi @ejolly! 
For now you can fix this like that. 

Chnage:
```javascript
import RouterLink from 'svelte-easyroute-webpack/RouterLink.svelte'
```
To:
```javascript
import RouterLink from '!!svelte-loader!svelte-easyroute-webpack/RouterLink.svelte'
```

**Comment by lyohaplotinka** [comment]
I will try to fix this problem in the next release. Or, if I will not be able to cope with this, I'll definitely update docs. 

Thank you!

**Comment by ejolly** [comment]
Thanks for the quick response!

**Comment by ejolly** [comment]
If it's helpful I just came across this issue on the svelte webpack starter, in which Rich Harris mentioned he removed the exclude node_modules line as well: https://github.com/sveltejs/template-webpack/issues/4

**Comment by lyohaplotinka** [comment]
@ejolly
Yes, thank you, but I seen it already.
Now I am trying to find something more.
