### ISSUE TITLE
nested route

### ISSUE THREAD

**Issue by meiseayoung** [lyohaplotinka/svelte-easyroute#6]
nice work! is there some way to use nested route like **vue-router** 
router :  `{children:[{
   path: 'somePath',
   component: InnerComponent
}]}`  
template: `<router-view>`

**Comment by lyohaplotinka** [comment]
Hi @meiseayoung!
For now not, but I will try to make this in further releases, thank you for the idea!

**Comment by meiseayoung** [comment]
> Hi @meiseayoung!
> For now not, but I will try to make this in further releases, thank you for the idea!

well done. thx

**Comment by lyohaplotinka** [comment]
@meiseayoung I am happy to tell you that there are nested routes now in version 2.0!

**Comment by meiseayoung** [comment]
@lyohaplotinka I just tried the nested routes.it work well.  there is a bug i find. I browse the home page, then go to the nested route, here i click the browser back button to home page, the bug happen next step, i click the browser go forward button to the nested route, the nested component has not rendered.  In the source RouterOutlet.svelte file i find a function named changeComponent, i deleted the first line `if (prevRouteId === currentRouteId && !forceRemount) return`, then it works
